# Render deployment configuration for Phygital Frontend
# This file configures the frontend service on Render

services:
  - type: web
    name: phygital-frontend
    env: static
    plan: free
    region: oregon
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://phygital-backend.onrender.com/api
      - key: VITE_FRONTEND_URL
        value: https://phygital-frontend.onrender.com
      - key: VITE_NODE_ENV
        value: production
