services:
  - type: web
    name: phygital-frontend
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://phygital-backend.onrender.com/api
      - key: VITE_FRONTEND_URL
        value: https://phygital-frontend.onrender.com
      - key: VITE_NODE_ENV
        value: production
      - key: VITE_ENABLE_ANALYTICS
        value: true
      - key: VITE_ENABLE_ERROR_REPORTING
        value: true
      - key: VITE_ENABLE_PWA
        value: false
      - key: VITE_ENABLE_OFFLINE_MODE
        value: false
      - key: VITE_ENABLE_SERVICE_WORKER
        value: false
      - key: VITE_CACHE_DURATION
        value: 3600
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
